language: R
warnings_are_errors: true
sudo: false
cache: packages

matrix:
    include:
        - r: devel
        - r: release
          after_success:
              - Rscript -e "covr::codecov()"
        - r: oldrel
        - r: release
          os: osx
        - r: oldrel
          env: DEPS=cran
          os: osx
    allow_failures:
        - r: oldrel # until fAsianOptions update makes it there.

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr
