# discrete power law distribution, directly cribbed from poweRlaw
dpldis_paretoconv <- function(x, xmin, alpha) {
    #x <- x [round (x) >= round (xmin)]
    xmin <- floor (xmin)
    constant <- VGAM::zeta (alpha)
    if(xmin > 1) 
        constant <- constant - sum ((1:(xmin - 1)) ^ (-alpha))

    -alpha * log (x) - log (constant)
}

#' Compares paretoconv with poweRlaw distributions
#'
#' This function extends directly from the \code{poweRlaw} function of the same
#' name, and compares a discrete power law distribution from the \code{poweRlaw}
#' package with an equivalent convoluted distribution generated by
#' \code{paretoconv}.
#'
#' @param d1 Discrete power law distribution of class \code{displ} from the
#' package \code{poweRlaw}.
#' @param d2 Equivalent convoluted values for the probability density function
#' obtained from \code{paretoconv (..., cdf=FALSE)}
#'
#' @export
#' @examples
#' \dontrun{
#' data ("native_american", package="poweRlaw")
#' m1 <- displ$new(native_american$Cas)
#' m1$setXmin (3)
#' m1$setPars (estimate_pars(m1))
#' x <- sort (unique (native_american$Cas))
#' y <- paretoconv (x=x, a=m1$getPars (), x0=3, n=2, cdf=FALSE, quiet=FALSE)
#' compare_conv_distributions (m1, y)
#' }
compare_conv_distributions <- function (d1, d2) 
{
    if (!is (d2, "displ"))
        stop ("Second argument must be a powerLaw::displ")

    xs <- sort (d2$getDat ())
    x <- unique (xs)
    if (!is.numeric (d1))
        stop ("First argument must be a vector")
    if (length (d1) != length (x))
        stop ("Length of second argument does not correspond to data in first argument")
    d1 <- log (d1 [match (xs, x)])

    d2 <- dpldis_paretoconv (xs, d2$getXmin (), d2$getPars ())
    ll_ratio_pts <- d1 - d2
    m <- mean (ll_ratio_pts [is.finite (ll_ratio_pts)])
    s <- sd (ll_ratio_pts [is.finite (ll_ratio_pts)])
    v <- sqrt (length (ll_ratio_pts)) * m / s
    p1 <- pnorm (v)
  
    if (p1 < 0.5) { p2 <- 2 * p1 } else { p2 <- 2 * (1 - p1) }

    l <- list (test_statistic = v, p_one_sided = 1 - p1, p_two_sided=p2, 
              ratio = data.frame (x=xs, ratio=ll_ratio_pts))
    class(l) <- "compare_distributions"
    return(l)
}
